export const _learning_path = {
    title: "Switch from IT to Software Development",
    milestones: [
        {
            id: 0,
            index: 0,
            source: "External",
            type: "Course",
            title: "Google IT Support certification on Coursera",
            description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. `,
            duration: "2 Weeks",
            link: "",
            completed: true,
        },
        {
            id: 1,
            index: 1,
            source: "Internal",
            type: "Course",
            title: "Department IT Course",
            description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. `,
            duration: "2 Weeks",
            link: "",
            completed: false,
        },
        {
            id: 2,
            index: 2,
            source: "Internal",
            type: "Activity",
            title: "Write a summary for your Journey",
            description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. `,
            duration: "2 Weeks",
            link: "",
            completed: false,
        },
        {
            id: 3,
            index: 3,
            source: "Internal",
            type: "Mentorship",
            title: "Connect with Emanuel from IT",
            description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. `,
            duration: "1 Day",
            link: "",
            completed: true,
        },
    ],
};

export const _profile = {
    first_name: "John",
    last_name: "Doe",
    department: "Corporate Development",
    current_role: "Business Operations Manager",
    groups: ["Latinx Employee Resource Group", "Young Professionals Network"],
};

export const _departments = [
    "Corporate Finance",
    "Wealth Management",
    "Risk Management",
    "Treasury",
    "Financial Planning & Analysis (FP&A)",
    "Tax",
    "Software Engineering",
    "Cloud Infrastructure",
    "Cybersecurity",
    "Data Science & AI",
    "IT Support",
    "Product Development",
    "Business Operations",
    "Logistics & Supply Chain",
    "Project Management",
    "Quality Assurance",
    "Customer Service",
    "Recruitment",
    "Employee Relations",
    "Learning & Development",
    "Compensation & Benefits",
    "Diversity, Equity, and Inclusion (DEI)",
    "Digital Marketing",
    "Brand Management",
    "Public Relations",
    "Product Marketing",
    "Market Research",
    "Enterprise Sales",
    "Account Management",
    "Business Development",
    "Client Success",
    "Corporate Governance",
    "Compliance",
    "Contracts",
    "Regulatory Affairs",
    "Intellectual Property",
    "Strategic Planning",
    "Mergers & Acquisitions (M&A)",
    "Corporate Development",
    "Competitive Analysis",
    "Product Research",
    "Technical Innovation",
    "Prototyping",
    "Market Testing"
];

export const _roles = [
    "Chief Executive Officer (CEO)",
    "Chief Financial Officer (CFO)",
    "Chief Technology Officer (CTO)",
    "Chief Operating Officer (COO)",
    "Chief Marketing Officer (CMO)",
    "Chief Human Resources Officer (CHRO)",
    "Chief Information Security Officer (CISO)",
    "Vice President of Finance",
    "Vice President of Technology",
    "Vice President of Operations",
    "Vice President of Marketing",
    "Vice President of Sales",
    "Vice President of Human Resources",
    "Vice President of Corporate Strategy",
    "Finance Manager",
    "Financial Analyst",
    "Risk Analyst",
    "Investment Manager",
    "Wealth Management Advisor",
    "Tax Specialist",
    "Treasury Analyst",
    "Corporate Accountant",
    "Software Engineer",
    "Senior Software Engineer",
    "Cloud Architect",
    "Cybersecurity Analyst",
    "Data Scientist",
    "AI/ML Engineer",
    "IT Support Specialist",
    "Product Manager",
    "Product Owner",
    "Scrum Master",
    "DevOps Engineer",
    "System Administrator",
    "Business Operations Manager",
    "Project Manager",
    "Quality Assurance Analyst",
    "Customer Service Manager",
    "Customer Support Specialist",
    "Human Resources Manager",
    "Recruitment Specialist",
    "Learning & Development Manager",
    "Employee Relations Specialist",
    "Compensation & Benefits Analyst",
    "DEI Manager",
    "Marketing Manager",
    "Digital Marketing Specialist",
    "Brand Manager",
    "Public Relations Specialist",
    "Content Marketing Manager",
    "SEO Specialist",
    "Sales Manager",
    "Account Executive",
    "Business Development Manager",
    "Sales Representative",
    "Client Success Manager",
    "Corporate Lawyer",
    "Compliance Officer",
    "Contracts Manager",
    "Regulatory Affairs Specialist",
    "Intellectual Property Attorney",
    "Strategic Planner",
    "Mergers & Acquisitions Analyst",
    "Corporate Development Manager",
    "Competitive Intelligence Analyst",
    "R&D Manager",
    "Product Research Analyst",
    "Technical Innovation Lead",
    "Prototype Engineer",
    "Market Testing Specialist",
    "Executive Assistant",
    "Office Manager",
    "IT Security Consultant"
];

export const _suggestions = [
    {
        title: "Get CompTIA certification",
        description:
            "Recent job positing on company website show that they are requiring this certification for new-hires ",
    },
    {
        title: "Learn web development",
        description:
            "Since you want to transition to the Software development department, having this skill will really set you apart",
    },
];

export const _groups = ["ACME Women", "ACME Black", "ACME with Disabilities"];


export const _learning_path_updated = {
    title: "Switch from IT to Software Development",
    milestones: [
      {
        index: 0,
        source: "External",
        type: "Course",
        title: "CompTIA certification on Coursera",
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. `,
        duration: "2 Weeks",
        link: "", completed:false,
      },
      {
        index: 0,
        source: "Internal",
        type: "Unknown",
        title: "IT Course on LMS",
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. `,
        duration: "2 Weeks",
        link: "", completed:false,
      },
      {
        index: 0,
        source: "Internal",
        type: "Activity",
        title: "Write a summary for your Journey",
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. `,
        duration: "2 Weeks",
        link: "", completed:false,
      },
      {
        index: 0,
        source: "Internal",
        type: "Mentorship",
        title: "Connect with Emanuel from IT",
        description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. `,
        duration: "1 Day",
        link: "", completed:false,
      },
    ],
  };